service: ${file(../config.yml):projectName}-dynamodb

frameworkVersion: '3'

plugins:
  - serverless-stage-manager

custom:
  stages: ${file(../stages.yml):stages}

provider:
  name: ${file(../config.yml):platform}
  stage: ${opt:stage, file(../config.yml):defaultStage}
  region: ${file(../config.yml):region}
  profile: ${file(../config.yml):profile}

resources:
  Resources:
    UserGameTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${file(../config.yml):projectName}-${self:provider.stage}-UserGameTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: gameId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    UserCloudSaveTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${file(../config.yml):projectName}-${self:provider.stage}-UserCloudSaveTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST