service: ${file(../config.yml):projectName}-dynamodb

frameworkVersion: '3'

plugins:
  - serverless-stage-manager

custom:
  stages: ${file(../stages.yml):stages}

provider:
  name: ${file(../config.yml):platform}
  stage: ${opt:stage, file(../config.yml):defaultStage}
  region: ${file(../config.yml):region}
  profile: ${file(../config.yml):profile}

resources:
  Resources:
    UserRecordTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${file(../config.yml):projectName}-${self:provider.stage}-UserRecordTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: recordId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: recordId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST