service: game-cloud-save

frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript
  - serverless-plugin-split-stacks
  - serverless-stage-manager
  - serverless-webpack

custom:
  splitStacks:
    perFunction: false
    perType: true
  stages:
    - dev
  webpack:
    includeModules: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: gameCloudSave
  runtime: nodejs14.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    Stage: ${self:provider.stage}
    Region: ${self:provider.region}
    # DynamoDB Tables
    UserStorageTable: ${self:service}-${self:provider.stage}-user-storage

  httpApi:
    authorizers:
      userAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - ${self:provider.region}
              - '.amazonaws.com/'
              - Ref: UserPool
        audience:
          - Ref: UserPoolClient

functions:


resources:
  - ${file(./resources/dynamodb-table.yml)}
  - ${file(./resources/s3-bucket.yml)}
  - ${file(./resources/cognito-user-pool.yml)}
  - ${file(./resources/api-gateway.yml)}