service: game-cloud-save-lambda

frameworkVersion: '3'

plugins:
  - serverless-stage-manager
  - serverless-iam-roles-per-function
  - serverless-plugin-split-stacks
  - serverless-webpack

custom:
  stages: ${file(../stages.yml):stages}
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules: true
  authorizers:
    userAuthorizer:
      type: jwt
      id: !ImportValue ${file(../config.yml):projectName}-${self:provider.stage}-HttpApiAuthorizerUserAuthorizerId

provider:
  name: ${file(../config.yml):platform}
  stage: ${opt:stage, file(../config.yml):defaultStage}
  region: ${file(../config.yml):region}
  profile: ${file(../config.yml):profile}
  runtime: ${file(../config.yml):runtime}
  logRetentionInDays: ${file(../config.yml):logRetentionInDays}
  versionFunctions: ${file(../config.yml):versionFunctions}

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    Stage: ${self:provider.stage}
    Region: ${self:provider.region}
    # DynamoDB Tables
    UserGameTable: ${file(../config.yml):projectName}-${self:provider.stage}-UserGameTable
    UserCloudSaveTable: ${file(../config.yml):projectName}-${self:provider.stage}-UserCloudSaveTable
    # S3 Bucket
    StorageBucket: ${file(../config.yml):projectName}-${self:provider.stage}-storagebucket
    # Cognito Client
    UserPoolClientId: !ImportValue ${file(../config.yml):projectName}-${self:provider.stage}-UserPoolClientId

  httpApi:
    id: !ImportValue ${file(../config.yml):projectName}-${self:provider.stage}-HttpApiId

functions:
  authService:
    handler: functions/authService/authService.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'cognito-idp:InitiateAuth'
        Resource:
          Fn::Join:
            - ''
            - - 'arn:aws:cognito-idp:'
              - ${self:provider.region}
              - ':'
              - Ref: AWS::AccountId
              - ':userpool/'
              - !ImportValue ${file(../config.yml):projectName}-${self:provider.stage}-UserPoolId
    events:
      - httpApi:
          path: /authService/userAuth
          method: POST
  gameService:
    handler: functions/gameService/gameService.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:Query'
        Resource:
          Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - ${self:provider.region}
              - ':'
              - Ref: AWS::AccountId
              - ':table/'
              - ${self:provider.environment.UserGameTable}
    events:
      - httpApi:
          path: /gameService/getAllGames
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
      - httpApi:
          path: /gameService/addGame
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
      - httpApi:
          path: /gameService/updateGame
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
  cloudSaveService:
    handler: functions/cloudSaveService/cloudSaveService.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:Query'
        Resource:
          Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - ${self:provider.region}
              - ':'
              - Ref: AWS::AccountId
              - ':table/'
              - ${self:provider.environment.UserCloudSaveTable}
      - Effect: Allow
        Action:
          - 's3:GetObject'
          - 's3:PutObject'
          - 's3:ListBucket'
        Resource:
          Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - ${self:provider.environment.StorageBucket}
              - '/cloudSaves/*'
    events:
      - httpApi:
          path: /cloudSaveService/getAllCloudSaves
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
      - httpApi:
          path: /cloudSaveService/requestUploadCloudSave
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
      - httpApi:
          path: /cloudSaveService/completeUploadCloudSave
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}
      - httpApi:
          path: /cloudSaveService/requestDownloadCloudSave
          method: POST
          authorizer: ${self:custom.authorizers.userAuthorizer}